using System.Globalization;
using RevitAi.Core.Tools;

namespace RevitAi.Core.Localization;

/// <summary>
/// Panel texts in English and Romanian. English is the default and the fallback for any missing key.
/// The AI's own instructions stay in English; the AI answers in the language the user writes in.
/// </summary>
public sealed class UiText
{
    public const string English = "en";
    public const string Romanian = "ro";

    public static readonly IReadOnlyList<string> SupportedLanguages = [English, Romanian];

    private readonly IReadOnlyDictionary<string, string> _strings;

    public UiText(string language)
    {
        Language = IsSupported(language) ? language : English;
        _strings = Language == Romanian ? RomanianStrings : EnglishStrings;
        Culture = CultureInfo.GetCultureInfo(Language == Romanian ? "ro-RO" : "en-GB");
    }

    public string Language { get; }

    public CultureInfo Culture { get; }

    /// <summary>English name of the language, for the AI instructions.</summary>
    public string LanguageName => Language == Romanian ? "Romanian" : "English";

    public string this[string key] =>
        _strings.TryGetValue(key, out string? text) ? text
        : EnglishStrings.TryGetValue(key, out string? fallback) ? fallback
        : key;

    public static bool IsSupported(string? language) => language is not null && SupportedLanguages.Contains(language);

    public string Format(string key, params object[] args) => string.Format(Culture, this[key], args);

    public string SelectedElements(int count) => Format(PluralKey("Selection", count), count);

    public string ProgressFor(ITool tool) => _strings.TryGetValue("Progress." + tool.Name, out string? label) ? label : tool.ProgressLabel;

    /// <summary>
    /// English: one / other. Romanian: one; "few" for 0 and numbers ending in 01–19; "many" (with "de") otherwise.
    /// </summary>
    private string PluralKey(string stem, int count)
    {
        if (count == 1)
        {
            return stem + "One";
        }

        int lastTwo = count % 100;
        bool romanianMany = Language == Romanian && count != 0 && (lastTwo == 0 || lastTwo >= 20);
        return stem + (romanianMany ? "Many" : "Few");
    }

    internal static readonly IReadOnlyDictionary<string, string> EnglishStrings = new Dictionary<string, string>
    {
        ["Refresh"] = "Refresh",
        ["RefreshTip"] = "Read the current context from Revit",
        ["ApiKey"] = "API key",
        ["ApiKeyTip"] = "Add, change or remove your OpenAI API key",
        ["LanguageToggle"] = "Română",
        ["LanguageToggleTip"] = "Show the panel in Romanian",
        ["ConsentTitle"] = "Before you start",
        ["ConsentBody"] = "To answer questions, Revit AI sends what you type and parts of your model to OpenAI: element names, categories, types, parameter values, levels and views. OpenAI's API data policies apply. Nothing is sent until you accept.",
        ["ConsentAccept"] = "I understand, continue",
        ["KeyTitle"] = "OpenAI API key",
        ["KeyHelp"] = "Create one at platform.openai.com. It is stored encrypted for your Windows account and only sent to OpenAI.",
        ["Save"] = "Save",
        ["Remove"] = "Remove",
        ["Preview"] = "Preview",
        ["PreviewTip"] = "Run the plan in Revit and roll it back, to see the real result and warnings",
        ["Apply"] = "Apply",
        ["ApplyTip"] = "Make these changes. They become one undo step (Ctrl+Z).",
        ["Discard"] = "Discard",
        ["Send"] = "Send",
        ["Cancel"] = "Cancel",
        ["Footer"] = "Nothing in your model changes until you click Apply. Each applied plan is one undo step (Ctrl+Z).",
        ["You"] = "You",
        ["Welcome"] = "Ask me about your model or what to change, for example: \"What did I select?\", \"How many doors are on this level?\", \"Make this wall 50 cm longer.\" I only propose changes; nothing changes until you click Apply.",
        ["NoProject"] = "No project open",
        ["SelectionOne"] = "{0} selected element",
        ["SelectionFew"] = "{0} selected elements",
        ["SelectionMany"] = "{0} selected elements",
        ["ProjectChangedConversation"] = "The active project changed, so I started a new conversation.",
        ["ProjectChangedPlan"] = "The active project changed, so I discarded the proposal. Nothing was changed.",
        ["PasteKeyFirst"] = "Paste your OpenAI API key first.",
        ["KeySaved"] = "API key saved, encrypted for your Windows account.",
        ["KeySaveFailed"] = "I couldn't save the API key: {0}",
        ["KeyRemoved"] = "API key removed.",
        ["KeyRemoveFailed"] = "I couldn't remove the API key: {0}",
        ["AcceptNoticeFirst"] = "Please read and accept the data notice above first.",
        ["AddKeyFirst"] = "Add your OpenAI API key first, in the API key panel above.",
        ["PreviousPlanDiscarded"] = "I discarded the previous proposal; it was never applied.",
        ["Discarded"] = "Discarded the proposal. Nothing was changed.",
        ["Cancelled"] = "Cancelled.",
        ["OpenAiTimeout"] = "OpenAI didn't answer within {0} seconds. Please try again.",
        ["CouldNotReachOpenAi"] = "I couldn't reach OpenAI. Check your internet connection and try again.",
        ["SomethingWrong"] = "Something went wrong: {0}",
        ["AiInvalidKey"] = "OpenAI rejected the API key. Check it in the API key panel above.",
        ["AiRateLimited"] = "OpenAI's rate limit or quota was reached ({0}). Wait a moment, or check your OpenAI billing.",
        ["AiBadResponse"] = "OpenAI returned an answer I couldn't read. Please try again.",
        ["AiFailed"] = "The OpenAI request failed: {0}",
        ["RevitTimeout"] = "Revit didn't respond in time. It may be busy or showing a dialog; close it and try again.",
        ["ReadModelFailed"] = "I couldn't read the model: {0}",
        ["PlanHeader"] = "Proposed changes · not applied yet · operations: {0}",
        ["PlanPreviewRequired"] = " · preview required before Apply",
        ["StatusPreviewing"] = "Previewing in Revit. Nothing will be kept…",
        ["StatusApplying"] = "Applying changes in Revit…",
        ["PreviewTimeout"] = "Revit didn't start the preview in time (busy or showing a dialog). Nothing was changed. Try again.",
        ["ApplyTimeout"] = "Revit didn't start applying in time (busy or showing a dialog). Nothing was changed. Try again.",
        ["PreviewError"] = "Preview failed: {0}. Nothing was changed.",
        ["ApplyError"] = "Apply failed: {0}. Nothing was changed.",
        ["PreviewSucceeded"] = "Preview succeeded. It was rolled back, so nothing was kept:",
        ["PreviewFailedAtStep"] = "Preview failed at step {0}: {1}",
        ["PreviewAdjust"] = "Nothing was changed. Ask me to adjust the plan.",
        ["Applied"] = "Applied {0} change(s):",
        ["UndoHint"] = "Undo all of it with Ctrl+Z (\"{0}\").",
        ["ApplyFailedAtStep"] = "Nothing was changed. Step {0} ({1}) failed: {2}",
        ["StepsRolledBack"] = "Steps 1–{0} were rolled back too.",
        ["RevitWarning"] = "Revit warning: {0}",
        ["Thinking"] = "Thinking…",
        ["NoAnswer"] = "I don't have an answer for that.",
        ["StoppedAtLimit"] = "I stopped after {0} steps without reaching an answer. Try asking something more specific.",
        // Write tools and plan execution: plan lines, step outcomes and failure reasons.
        ["Tool.CatWalls"] = "walls",
        ["Tool.CatDoors"] = "doors",
        ["Tool.CatWindows"] = "windows",
        ["Tool.CatFloors"] = "floors",
        ["Tool.WallSummary"] = "Create wall '{0}' on {1}, {2} long, {3} high, from ({4:0}, {5:0}) to ({6:0}, {7:0})",
        ["Tool.WallCreated"] = "Created wall {0} ('{1}', {2}) on {3}",
        ["Tool.WallTooShort"] = "The wall would be {0} long; walls must be at least {1}.",
        ["Tool.WallHeightRange"] = "Wall height must be between 0 and {0}.",
        ["Tool.ModifyZero"] = "distanceMm must not be 0.",
        ["Tool.EndStart"] = "start",
        ["Tool.EndEnd"] = "end",
        ["Tool.ModifyReferenceSummary"] = "Change the length of {0} by {1:+0;-0} mm at its {2}",
        ["Tool.ModifySummary"] = "Wall {0}: {1} → {2} (moves its {3})",
        ["Tool.ModifyDone"] = "Wall {0}: {1} → {2}",
        ["Tool.ModifyTooShort"] = "Wall {0} is {1} long; it can't be shortened by {2}.",
        ["Tool.RoomSummary"] = "Create room on {0} at ({1:0}, {2:0})",
        ["Tool.RoomSummaryNamed"] = "Create room '{0}' on {1} at ({2:0}, {3:0})",
        ["Tool.RoomNotEnclosed"] = "The point ({0:0}, {1:0}) isn't inside an area enclosed by walls or room separation lines, so the room would not be enclosed.",
        ["Tool.RoomCreated"] = "Created room {0} '{1}' ({2:0.##} m²) on {3}",
        ["Tool.Door"] = "door",
        ["Tool.Window"] = "window",
        ["Tool.WallRef"] = "wall {0}",
        ["Tool.HostedSummary"] = "Place {0} '{1}' in {2}, centred {3} from its start",
        ["Tool.SillSuffix"] = ", sill {0}",
        ["Tool.DoorPlaced"] = "Placed door {0} ('{1}') in wall {2}",
        ["Tool.WindowPlaced"] = "Placed window {0} ('{1}') in wall {2}",
        ["Tool.SillNotEditable"] = "Window type '{0}' has no editable sill height.",
        ["Tool.SillRange"] = "The sill height must be between 0 and {0}.",
        ["Tool.OffsetOutside"] = "The position {0} is outside the wall, which is {1} long.",
        ["Tool.NotHosted"] = "The {0} could not be hosted in wall {1}.",
        ["Tool.WallNoLevel"] = "Wall {0} has no base level.",
        ["Tool.FloorSummary"] = "Create floor '{0}' on {1}, {2} corners, {3:0.##} m²",
        ["Tool.FloorCreated"] = "Created floor {0} ('{1}', {2:0.##} m²) on {3}",
        ["Tool.FloorTooFewPoints"] = "A floor boundary needs at least 3 points.",
        ["Tool.FloorShortEdge"] = "Boundary edges must be at least {0} long (check for repeated points).",
        ["Tool.FloorSelfIntersects"] = "The boundary crosses or touches itself.",
        ["Tool.FloorNoArea"] = "The boundary encloses no area (are the points in a line?).",
        ["Tool.NotALevel"] = "Element {0} is not a level.",
        ["Tool.NotAWall"] = "Element {0} is not a wall.",
        ["Tool.NotStraight"] = "Wall {0} is not straight; only straight walls are supported.",
        ["Tool.NoDefaultType"] = "The project has no default type for {0}. Use the typeId of an existing element.",
        ["Tool.NotAType"] = "Element {0} is not a type for {1}.",
        ["Tool.WrongCategoryType"] = "Type {0} ({1}) is not a type for {2}.",
        ["Tool.IdOrReference"] = "{0} must be an element ID or a reference like $op1.elementId.",
        ["Tool.UnresolvedReference"] = "{0} still contains an unresolved reference.",
        ["Plan.NotWriteTool"] = "'{0}' is not an available write tool.",
        ["Plan.RevitRefused"] = "Revit refused the operation: {0}",
        ["Plan.NotAccepted"] = "Revit did not accept the change ({0}).",

        // Documentation tools (Phase 4).
        ["Tool.CatTitleBlocks"] = "title blocks",
        ["Tool.FloorPlan"] = "floor plan",
        ["Tool.CeilingPlan"] = "ceiling plan",
        ["Tool.ViewSummary"] = "Create {0} '{1}' for {2}",
        ["Tool.ViewSummaryUnnamed"] = "Create {0} for {1}",
        ["Tool.TemplateSuffix"] = ", template '{0}'",
        ["Tool.ViewCreated"] = "Created view {0} '{1}'",
        ["Tool.ViewNameTaken"] = "A view named '{0}' already exists.",
        ["Tool.NoViewFamilyType"] = "The project has no view type for a {0}.",
        ["Tool.NotATemplate"] = "Element {0} is not a view template.",
        ["Tool.SheetSummary"] = "Create sheet {0} '{1}' with title block '{2}'",
        ["Tool.SheetViewsSuffix"] = ", placing {0} view(s)",
        ["Tool.SheetCreated"] = "Created sheet {0} '{1}' (ID {2}) and placed {3} view(s)",
        ["Tool.SheetNumberTaken"] = "A sheet numbered '{0}' already exists.",
        ["Tool.SheetNumberEmpty"] = "The sheet number is empty.",
        ["Tool.NotAPlaceableView"] = "Element {0} is not a view that can be placed on a sheet.",
        ["Tool.ViewOnSheet"] = "View '{0}' is already on sheet {1}.",
        ["Tool.CannotPlaceView"] = "View '{0}' can't be placed on this sheet.",
        ["Tool.ScheduleSummary"] = "Create schedule '{0}' of {1} with fields: {2}",
        ["Tool.ScheduleCreated"] = "Created schedule {0} '{1}' with {2} field(s)",
        ["Tool.ScheduleNameTaken"] = "A schedule named '{0}' already exists.",
        ["Tool.ScheduleNoFields"] = "Give at least one field.",
        ["Tool.ScheduleUnknownField"] = "'{0}' is not a field of {1} schedules. Available fields include: {2}",
        ["Tool.ScheduleCategory"] = "{0} can't be scheduled.",
        ["Tool.TagSummary"] = "Tag {0} untagged {1} in view '{2}'",
        ["Tool.TagSummaryRef"] = "Tag untagged {0} in view {1}",
        ["Tool.TagSummaryIds"] = "Tag {0} element(s) in view '{1}'",
        ["Tool.TagsCreated"] = "Added {0} tag(s) in view '{1}'",
        ["Tool.NothingToTag"] = "There is nothing untagged to tag in view '{0}'.",
        ["Tool.ViewNotTaggable"] = "View '{0}' ({1}) can't hold tags; use a plan, section or elevation.",
        ["Tool.TagNeedsTarget"] = "Give either a category or elementIds, not both.",
        ["Tool.NotAView"] = "Element {0} is not a view.",
        ["Tool.TextSummary"] = "Add text \"{0}\" in view '{1}' at ({2:0}, {3:0})",
        ["Tool.TextCreated"] = "Added text note {0} in view '{1}'",
        ["Tool.TextEmpty"] = "The text is empty.",
        ["Tool.ViewNoAnnotation"] = "View '{0}' ({1}) can't hold annotations.",
        ["Tool.NoTextType"] = "The project has no default text type.",
        ["Tool.DimSummary"] = "Dimension {0} ({1}) in view '{2}', {3} from the wall",
        ["Tool.DimCreated"] = "Added dimension {0} ({1}) to wall {2}",
        ["Tool.DimNoEnds"] = "Couldn't find both end faces of wall {0} in this view (it may be joined to other walls at its ends).",
        ["Tool.ViewNotPlan"] = "View '{0}' is not a plan view.",
        ["Tool.NamedSuffix"] = " '{0}'",
        ["Tool.SectionSummary"] = "Create section{0} along ({1:0}, {2:0}) → ({3:0}, {4:0}), {5} deep, {6} high above {7}, looking to the left of that direction",
        ["Tool.SectionCreated"] = "Created section {0} '{1}'",
        ["Tool.SectionTooShort"] = "The section line must be at least {0} long.",
        ["Tool.SectionRange"] = "Depth and height must be between 0 and {0}.",
        ["Tool.North"] = "north",
        ["Tool.East"] = "east",
        ["Tool.South"] = "south",
        ["Tool.West"] = "west",
        ["Tool.ElevationSummary"] = "Create elevation(s) looking {0} from ({1:0}, {2:0}), with the marker in view '{3}'",
        ["Tool.ElevationCreated"] = "Created elevation view(s): {0}",
        ["Tool.ElevationNeedsDirection"] = "Give at least one direction.",
        ["Tool.ElevationNoSlot"] = "Couldn't create an elevation looking {0} from this marker.",
        ["Tool.ThreeDSummary"] = "Create 3D view{0}{1}",
        ["Tool.SectionBoxSuffix"] = ", cropped around {0} element(s)",
        ["Tool.ThreeDCreated"] = "Created 3D view {0} '{1}'",
        ["Tool.NoBoundingBox"] = "Element {0} has no geometry to crop around.",
        ["Tool.RoomDimSummary"] = "Dimension the width and depth of room {0} in view '{1}'",
        ["Tool.RoomDimCreated"] = "Added {0} dimension(s) to room {1}: {2}",
        ["Tool.NotARoom"] = "Element {0} is not a room.",
        ["Tool.RoomNotPlaced"] = "Room {0} is not placed or not enclosed.",
        ["Tool.RoomNoOppositeWalls"] = "Couldn't find two opposite straight walls around room {0} to dimension.",
        ["Tool.MoveSummary"] = "Move {0} element(s) by ({1:0}, {2:0}) mm: {3}",
        ["Tool.MoveDone"] = "Moved {0} element(s) by ({1:0}, {2:0}) mm",
        ["Tool.MoveZero"] = "The move distance is zero.",
        ["Tool.MoveTooFar"] = "Moves are limited to {0}.",
        ["Tool.Pinned"] = "Element {0} is pinned; unpin it in Revit first.",
        ["Tool.MoveNeedsElements"] = "Give at least one element.",
    };


    internal static readonly IReadOnlyDictionary<string, string> RomanianStrings = new Dictionary<string, string>
    {
        ["Refresh"] = "Reîmprospătează",
        ["RefreshTip"] = "Citește contextul curent din Revit",
        ["ApiKey"] = "Cheie API",
        ["ApiKeyTip"] = "Adaugă, schimbă sau șterge cheia ta API OpenAI",
        ["LanguageToggle"] = "English",
        ["LanguageToggleTip"] = "Afișează panoul în engleză",
        ["ConsentTitle"] = "Înainte de a începe",
        ["ConsentBody"] = "Pentru a răspunde la întrebări, Revit AI trimite la OpenAI ce scrii și părți din modelul tău: nume de elemente, categorii, tipuri, valori ale parametrilor, niveluri și vederi. Se aplică politicile OpenAI privind datele trimise prin API. Nu se trimite nimic până nu accepți.",
        ["ConsentAccept"] = "Am înțeles, continuă",
        ["KeyTitle"] = "Cheie API OpenAI",
        ["KeyHelp"] = "Creează una pe platform.openai.com. Este stocată criptat pentru contul tău Windows și este trimisă doar către OpenAI.",
        ["Save"] = "Salvează",
        ["Remove"] = "Șterge",
        ["Preview"] = "Previzualizează",
        ["PreviewTip"] = "Rulează planul în Revit și anulează-l, ca să vezi rezultatul real și avertismentele",
        ["Apply"] = "Aplică",
        ["ApplyTip"] = "Fă aceste modificări. Devin un singur pas de anulare (Ctrl+Z).",
        ["Discard"] = "Renunță",
        ["Send"] = "Trimite",
        ["Cancel"] = "Oprește",
        ["Footer"] = "Nimic nu se schimbă în model până nu apeși Aplică. Fiecare plan aplicat este un singur pas de anulare (Ctrl+Z).",
        ["You"] = "Tu",
        ["Welcome"] = "Întreabă-mă despre model sau ce să modific, de exemplu: „Ce am selectat?”, „Câte uși sunt pe acest nivel?”, „Prelungește acest perete cu 50 cm.” Eu doar propun modificări; nimic nu se schimbă până nu apeși Aplică.",
        ["NoProject"] = "Niciun proiect deschis",
        ["SelectionOne"] = "{0} element selectat",
        ["SelectionFew"] = "{0} elemente selectate",
        ["SelectionMany"] = "{0} de elemente selectate",
        ["ProjectChangedConversation"] = "Proiectul activ s-a schimbat, așa că am început o conversație nouă.",
        ["ProjectChangedPlan"] = "Proiectul activ s-a schimbat, așa că am renunțat la propunere. Nu s-a modificat nimic.",
        ["PasteKeyFirst"] = "Lipește mai întâi cheia ta API OpenAI.",
        ["KeySaved"] = "Cheia API a fost salvată, criptată pentru contul tău Windows.",
        ["KeySaveFailed"] = "Nu am putut salva cheia API: {0}",
        ["KeyRemoved"] = "Cheia API a fost ștearsă.",
        ["KeyRemoveFailed"] = "Nu am putut șterge cheia API: {0}",
        ["AcceptNoticeFirst"] = "Te rog să citești și să accepți mai întâi notificarea despre date de mai sus.",
        ["AddKeyFirst"] = "Adaugă mai întâi cheia API OpenAI, în panoul Cheie API de mai sus.",
        ["PreviousPlanDiscarded"] = "Am renunțat la propunerea anterioară; nu a fost aplicată.",
        ["Discarded"] = "Am renunțat la propunere. Nu s-a modificat nimic.",
        ["Cancelled"] = "Oprit.",
        ["OpenAiTimeout"] = "OpenAI nu a răspuns în timpul alocat ({0} s). Te rog să încerci din nou.",
        ["CouldNotReachOpenAi"] = "Nu am putut contacta OpenAI. Verifică conexiunea la internet și încearcă din nou.",
        ["SomethingWrong"] = "Ceva nu a mers bine: {0}",
        ["AiInvalidKey"] = "OpenAI a respins cheia API. Verific-o în panoul Cheie API de mai sus.",
        ["AiRateLimited"] = "S-a atins limita de cereri sau cota OpenAI ({0}). Așteaptă puțin sau verifică facturarea OpenAI.",
        ["AiBadResponse"] = "OpenAI a trimis un răspuns pe care nu l-am putut citi. Te rog să încerci din nou.",
        ["AiFailed"] = "Cererea către OpenAI a eșuat: {0}",
        ["RevitTimeout"] = "Revit nu a răspuns la timp. Poate este ocupat sau afișează un dialog; închide-l și încearcă din nou.",
        ["ReadModelFailed"] = "Nu am putut citi modelul: {0}",
        ["PlanHeader"] = "Modificări propuse · neaplicate încă · operații: {0}",
        ["PlanPreviewRequired"] = " · previzualizarea este obligatorie înainte de Aplică",
        ["StatusPreviewing"] = "Previzualizare în Revit. Nu se va păstra nimic…",
        ["StatusApplying"] = "Se aplică modificările în Revit…",
        ["PreviewTimeout"] = "Revit nu a pornit previzualizarea la timp (este ocupat sau afișează un dialog). Nu s-a modificat nimic. Încearcă din nou.",
        ["ApplyTimeout"] = "Revit nu a pornit aplicarea la timp (este ocupat sau afișează un dialog). Nu s-a modificat nimic. Încearcă din nou.",
        ["PreviewError"] = "Previzualizarea a eșuat: {0}. Nu s-a modificat nimic.",
        ["ApplyError"] = "Aplicarea a eșuat: {0}. Nu s-a modificat nimic.",
        ["PreviewSucceeded"] = "Previzualizarea a reușit. A fost anulată, deci nu s-a păstrat nimic:",
        ["PreviewFailedAtStep"] = "Previzualizarea a eșuat la pasul {0}: {1}",
        ["PreviewAdjust"] = "Nu s-a modificat nimic. Cere-mi să ajustez planul.",
        ["Applied"] = "Am aplicat modificările ({0}):",
        ["UndoHint"] = "Anulezi totul cu Ctrl+Z („{0}”).",
        ["ApplyFailedAtStep"] = "Nu s-a modificat nimic. Pasul {0} ({1}) a eșuat: {2}",
        ["StepsRolledBack"] = "Au fost anulați și pașii 1–{0}.",
        ["RevitWarning"] = "Avertisment Revit: {0}",
        ["Thinking"] = "Mă gândesc…",
        ["NoAnswer"] = "Nu am un răspuns pentru asta.",
        ["StoppedAtLimit"] = "M-am oprit după {0} pași fără să ajung la un răspuns. Încearcă o întrebare mai precisă.",

        ["Tool.CatWalls"] = "pereți",
        ["Tool.CatDoors"] = "uși",
        ["Tool.CatWindows"] = "ferestre",
        ["Tool.CatFloors"] = "pardoseli",
        ["Tool.WallSummary"] = "Creează peretele „{0}” pe {1}, lung de {2}, înalt de {3}, de la ({4:0}, {5:0}) la ({6:0}, {7:0})",
        ["Tool.WallCreated"] = "Am creat peretele {0} („{1}”, {2}) pe {3}",
        ["Tool.WallTooShort"] = "Peretele ar avea {0}; un perete trebuie să aibă cel puțin {1}.",
        ["Tool.WallHeightRange"] = "Înălțimea peretelui trebuie să fie între 0 și {0}.",
        ["Tool.ModifyZero"] = "distanceMm nu poate fi 0.",
        ["Tool.EndStart"] = "capătul de început",
        ["Tool.EndEnd"] = "capătul de sfârșit",
        ["Tool.ModifyReferenceSummary"] = "Modifică lungimea pentru {0} cu {1:+0;-0} mm la {2}",
        ["Tool.ModifySummary"] = "Peretele {0}: {1} → {2} (se mută {3})",
        ["Tool.ModifyDone"] = "Peretele {0}: {1} → {2}",
        ["Tool.ModifyTooShort"] = "Peretele {0} are {1}; nu poate fi scurtat cu {2}.",
        ["Tool.RoomSummary"] = "Creează o cameră pe {0} în punctul ({1:0}, {2:0})",
        ["Tool.RoomSummaryNamed"] = "Creează camera „{0}” pe {1} în punctul ({2:0}, {3:0})",
        ["Tool.RoomNotEnclosed"] = "Punctul ({0:0}, {1:0}) nu se află într-o zonă închisă de pereți sau de linii de separare, deci camera nu ar fi închisă.",
        ["Tool.RoomCreated"] = "Am creat camera {0} „{1}” ({2:0.##} m²) pe {3}",
        ["Tool.Door"] = "ușa",
        ["Tool.Window"] = "fereastra",
        ["Tool.WallRef"] = "peretele {0}",
        ["Tool.HostedSummary"] = "Plasează {0} „{1}” în {2}, centrată la {3} de la început",
        ["Tool.SillSuffix"] = ", parapet {0}",
        ["Tool.DoorPlaced"] = "Am plasat ușa {0} („{1}”) în peretele {2}",
        ["Tool.WindowPlaced"] = "Am plasat fereastra {0} („{1}”) în peretele {2}",
        ["Tool.SillNotEditable"] = "Tipul de fereastră „{0}” nu are înălțimea parapetului editabilă.",
        ["Tool.SillRange"] = "Înălțimea parapetului trebuie să fie între 0 și {0}.",
        ["Tool.OffsetOutside"] = "Poziția {0} este în afara peretelui, care are {1}.",
        ["Tool.NotHosted"] = "Elementul ({0}) nu a putut fi găzduit în peretele {1}.",
        ["Tool.WallNoLevel"] = "Peretele {0} nu are nivel de bază.",
        ["Tool.FloorSummary"] = "Creează pardoseala „{0}” pe {1}, {2} colțuri, {3:0.##} m²",
        ["Tool.FloorCreated"] = "Am creat pardoseala {0} („{1}”, {2:0.##} m²) pe {3}",
        ["Tool.FloorTooFewPoints"] = "Conturul pardoselii are nevoie de cel puțin 3 puncte.",
        ["Tool.FloorShortEdge"] = "Laturile conturului trebuie să aibă cel puțin {0} (verifică punctele repetate).",
        ["Tool.FloorSelfIntersects"] = "Conturul se intersectează sau se atinge singur.",
        ["Tool.FloorNoArea"] = "Conturul nu delimitează nicio suprafață (punctele sunt pe o linie?).",
        ["Tool.NotALevel"] = "Elementul {0} nu este un nivel.",
        ["Tool.NotAWall"] = "Elementul {0} nu este un perete.",
        ["Tool.NotStraight"] = "Peretele {0} nu este drept; sunt acceptați doar pereți drepți.",
        ["Tool.NoDefaultType"] = "Proiectul nu are un tip implicit pentru {0}. Folosește typeId-ul unui element existent.",
        ["Tool.NotAType"] = "Elementul {0} nu este un tip pentru {1}.",
        ["Tool.WrongCategoryType"] = "Tipul {0} ({1}) nu este un tip pentru {2}.",
        ["Tool.IdOrReference"] = "{0} trebuie să fie un ID de element sau o referință de forma $op1.elementId.",
        ["Tool.UnresolvedReference"] = "{0} conține încă o referință nerezolvată.",
        ["Plan.NotWriteTool"] = "„{0}” nu este o unealtă de modificare disponibilă.",
        ["Plan.RevitRefused"] = "Revit a refuzat operația: {0}",
        ["Plan.NotAccepted"] = "Revit nu a acceptat modificarea ({0}).",
        ["Tool.CatTitleBlocks"] = "cartușe",
        ["Tool.FloorPlan"] = "un plan de nivel",
        ["Tool.CeilingPlan"] = "un plan de tavan",
        ["Tool.ViewSummary"] = "Creează {0} „{1}” pentru {2}",
        ["Tool.ViewSummaryUnnamed"] = "Creează {0} pentru {1}",
        ["Tool.TemplateSuffix"] = ", șablon „{0}”",
        ["Tool.ViewCreated"] = "Am creat vederea {0} „{1}”",
        ["Tool.ViewNameTaken"] = "Există deja o vedere numită „{0}”.",
        ["Tool.NoViewFamilyType"] = "Proiectul nu are un tip de vedere pentru {0}.",
        ["Tool.NotATemplate"] = "Elementul {0} nu este un șablon de vedere.",
        ["Tool.SheetSummary"] = "Creează planșa {0} „{1}” cu cartușul „{2}”",
        ["Tool.SheetViewsSuffix"] = ", vederi de plasat: {0}",
        ["Tool.SheetCreated"] = "Am creat planșa {0} „{1}” (ID {2}); vederi plasate: {3}",
        ["Tool.SheetNumberTaken"] = "Există deja o planșă cu numărul „{0}”.",
        ["Tool.SheetNumberEmpty"] = "Numărul planșei este gol.",
        ["Tool.NotAPlaceableView"] = "Elementul {0} nu este o vedere care poate fi plasată pe o planșă.",
        ["Tool.ViewOnSheet"] = "Vederea „{0}” este deja pe planșa {1}.",
        ["Tool.CannotPlaceView"] = "Vederea „{0}” nu poate fi plasată pe această planșă.",
        ["Tool.ScheduleSummary"] = "Creează tabelul „{0}” pentru {1}, cu câmpurile: {2}",
        ["Tool.ScheduleCreated"] = "Am creat tabelul {0} „{1}”; câmpuri: {2}",
        ["Tool.ScheduleNameTaken"] = "Există deja un tabel numit „{0}”.",
        ["Tool.ScheduleNoFields"] = "Indică cel puțin un câmp.",
        ["Tool.ScheduleUnknownField"] = "„{0}” nu este un câmp pentru tabelele de {1}. Câmpuri disponibile, de exemplu: {2}",
        ["Tool.ScheduleCategory"] = "Pentru {0} nu se poate crea un tabel.",
        ["Tool.TagSummary"] = "Adaugă etichete pentru {1} fără etichetă în vederea „{2}” (elemente: {0})",
        ["Tool.TagSummaryRef"] = "Adaugă etichete pentru {0} fără etichetă în vederea {1}",
        ["Tool.TagSummaryIds"] = "Adaugă etichete pentru elementele indicate în vederea „{1}” (elemente: {0})",
        ["Tool.TagsCreated"] = "Am adăugat etichete în vederea „{1}”: {0}",
        ["Tool.NothingToTag"] = "Nu există elemente fără etichetă în vederea „{0}”.",
        ["Tool.ViewNotTaggable"] = "Vederea „{0}” ({1}) nu poate avea etichete; folosește un plan, o secțiune sau o fațadă.",
        ["Tool.TagNeedsTarget"] = "Indică fie o categorie, fie elementIds, nu amândouă.",
        ["Tool.NotAView"] = "Elementul {0} nu este o vedere.",
        ["Tool.TextSummary"] = "Adaugă textul „{0}” în vederea „{1}” la ({2:0}, {3:0})",
        ["Tool.TextCreated"] = "Am adăugat nota de text {0} în vederea „{1}”",
        ["Tool.TextEmpty"] = "Textul este gol.",
        ["Tool.ViewNoAnnotation"] = "Vederea „{0}” ({1}) nu poate conține adnotări.",
        ["Tool.NoTextType"] = "Proiectul nu are un tip de text implicit.",
        ["Tool.DimSummary"] = "Cotează {0} ({1}) în vederea „{2}”, la {3} de perete",
        ["Tool.DimCreated"] = "Am adăugat cota {0} ({1}) peretelui {2}",
        ["Tool.DimNoEnds"] = "Nu am găsit ambele fețe de capăt ale peretelui {0} în această vedere (poate este îmbinat cu alți pereți la capete).",
        ["Tool.ViewNotPlan"] = "Vederea „{0}” nu este o vedere în plan.",
        ["Tool.NamedSuffix"] = " „{0}”",
        ["Tool.SectionSummary"] = "Creează secțiunea{0} de-a lungul ({1:0}, {2:0}) → ({3:0}, {4:0}), adâncime {5}, înălțime {6} peste {7}, privind spre stânga acestei direcții",
        ["Tool.SectionCreated"] = "Am creat secțiunea {0} „{1}”",
        ["Tool.SectionTooShort"] = "Linia secțiunii trebuie să aibă cel puțin {0}.",
        ["Tool.SectionRange"] = "Adâncimea și înălțimea trebuie să fie între 0 și {0}.",
        ["Tool.North"] = "nord",
        ["Tool.East"] = "est",
        ["Tool.South"] = "sud",
        ["Tool.West"] = "vest",
        ["Tool.ElevationSummary"] = "Creează fațade orientate spre {0} din punctul ({1:0}, {2:0}), cu marcajul în vederea „{3}”",
        ["Tool.ElevationCreated"] = "Am creat fațadele: {0}",
        ["Tool.ElevationNeedsDirection"] = "Indică cel puțin o direcție.",
        ["Tool.ElevationNoSlot"] = "Nu am putut crea o fațadă orientată spre {0} din acest marcaj.",
        ["Tool.ThreeDSummary"] = "Creează o vedere 3D{0}{1}",
        ["Tool.SectionBoxSuffix"] = ", decupată în jurul elementelor: {0}",
        ["Tool.ThreeDCreated"] = "Am creat vederea 3D {0} „{1}”",
        ["Tool.NoBoundingBox"] = "Elementul {0} nu are geometrie în jurul căreia să se decupeze.",
        ["Tool.RoomDimSummary"] = "Cotează lățimea și adâncimea camerei {0} în vederea „{1}”",
        ["Tool.RoomDimCreated"] = "Am adăugat cote camerei {1} ({0}): {2}",
        ["Tool.NotARoom"] = "Elementul {0} nu este o cameră.",
        ["Tool.RoomNotPlaced"] = "Camera {0} nu este plasată sau nu este închisă.",
        ["Tool.RoomNoOppositeWalls"] = "Nu am găsit doi pereți drepți opuși în jurul camerei {0} pentru cotare.",
        ["Tool.MoveSummary"] = "Mută elementele ({0}) cu ({1:0}, {2:0}) mm: {3}",
        ["Tool.MoveDone"] = "Am mutat elementele ({0}) cu ({1:0}, {2:0}) mm",
        ["Tool.MoveZero"] = "Distanța de mutare este zero.",
        ["Tool.MoveTooFar"] = "Mutările sunt limitate la {0}.",
        ["Tool.Pinned"] = "Elementul {0} este fixat (pinned); anulează fixarea în Revit mai întâi.",
        ["Tool.MoveNeedsElements"] = "Indică cel puțin un element.",
        ["Progress.move_elements"] = "Verific mutarea…",
        ["Progress.select_elements"] = "Selectez elementele în Revit…",
        ["Progress.find_rooms_without_tags"] = "Caut camerele fără etichetă…",
        ["Progress.find_unhosted_doors"] = "Caut ușile fără perete gazdă…",
        ["Progress.find_unhosted_windows"] = "Caut ferestrele fără perete gazdă…",
        ["Progress.find_duplicate_elements"] = "Caut elementele duplicate…",
        ["Progress.get_model_warnings"] = "Citesc avertismentele modelului…",
        ["Progress.find_nonstandard_elements"] = "Caut elementele care nu respectă standardele…",
        ["Progress.find_elements_missing_parameter"] = "Caut parametrii lipsă…",
        ["Progress.create_section"] = "Verific secțiunea…",
        ["Progress.create_elevations"] = "Verific fațadele…",
        ["Progress.create_3d_view"] = "Verific vederea 3D…",
        ["Progress.dimension_room"] = "Verific cotele camerei…",
        ["Progress.find_views"] = "Caut vederile…",
        ["Progress.create_view"] = "Verific vederea…",
        ["Progress.create_sheet"] = "Verific planșa…",
        ["Progress.create_schedule"] = "Verific tabelul…",
        ["Progress.tag_elements"] = "Verific etichetele…",
        ["Progress.create_text"] = "Verific textul…",
        ["Progress.dimension_wall"] = "Verific cota…",

        // Tool progress labels; English falls back to each tool's own ProgressLabel.
        ["Progress.get_project_info"] = "Citesc informațiile proiectului…",
        ["Progress.get_active_view"] = "Citesc vederea activă…",
        ["Progress.get_active_level"] = "Citesc nivelul activ…",
        ["Progress.get_selected_elements"] = "Citesc selecția…",
        ["Progress.get_element"] = "Citesc elementul…",
        ["Progress.find_elements"] = "Caut în model…",
        ["Progress.get_element_parameters"] = "Citesc parametrii…",
        ["Progress.find_family_types"] = "Caut tipurile disponibile…",
        ["Progress.get_project_standard_types"] = "Citesc tipurile standard ale proiectului…",
        ["Progress.find_nearby_elements"] = "Caut elementele din apropiere…",
        ["Progress.get_element_room"] = "Caut camera elementului…",
        ["Progress.get_room_boundary"] = "Citesc limitele camerei…",
        ["Progress.create_wall"] = "Verific peretele…",
        ["Progress.modify_wall"] = "Verific modificarea peretelui…",
        ["Progress.create_room"] = "Verific camera…",
        ["Progress.create_door"] = "Verific ușa…",
        ["Progress.create_window"] = "Verific fereastra…",
        ["Progress.create_floor"] = "Verific pardoseala…",
    };
}
