using System.Globalization;
using RevitAi.Core.Tools;

namespace RevitAi.Core.Localization;

/// <summary>
/// Panel texts in English and Romanian. English is the default and the fallback for any missing key.
/// The AI's own instructions stay in English; the AI answers in the language the user writes in.
/// </summary>
public sealed class UiText
{
    public const string English = "en";
    public const string Romanian = "ro";

    public static readonly IReadOnlyList<string> SupportedLanguages = [English, Romanian];

    private readonly IReadOnlyDictionary<string, string> _strings;

    public UiText(string language)
    {
        Language = IsSupported(language) ? language : English;
        _strings = Language == Romanian ? RomanianStrings : EnglishStrings;
        Culture = CultureInfo.GetCultureInfo(Language == Romanian ? "ro-RO" : "en-GB");
    }

    public string Language { get; }

    public CultureInfo Culture { get; }

    /// <summary>English name of the language, for the AI instructions.</summary>
    public string LanguageName => Language == Romanian ? "Romanian" : "English";

    public string this[string key] =>
        _strings.TryGetValue(key, out string? text) ? text
        : EnglishStrings.TryGetValue(key, out string? fallback) ? fallback
        : key;

    public static bool IsSupported(string? language) => language is not null && SupportedLanguages.Contains(language);

    public string Format(string key, params object[] args) => string.Format(Culture, this[key], args);

    public string SelectedElements(int count) => Format(PluralKey("Selection", count), count);

    public string ProgressFor(ITool tool) => _strings.TryGetValue("Progress." + tool.Name, out string? label) ? label : tool.ProgressLabel;

    /// <summary>
    /// English: one / other. Romanian: one; "few" for 0 and numbers ending in 01–19; "many" (with "de") otherwise.
    /// </summary>
    private string PluralKey(string stem, int count)
    {
        if (count == 1)
        {
            return stem + "One";
        }

        int lastTwo = count % 100;
        bool romanianMany = Language == Romanian && count != 0 && (lastTwo == 0 || lastTwo >= 20);
        return stem + (romanianMany ? "Many" : "Few");
    }

    internal static readonly IReadOnlyDictionary<string, string> EnglishStrings = new Dictionary<string, string>
    {
        ["Refresh"] = "Refresh",
        ["RefreshTip"] = "Read the current context from Revit",
        ["ApiKey"] = "API key",
        ["ApiKeyTip"] = "Choose the AI service and add, change or remove its API key",
        ["LanguageToggle"] = "Română",
        ["LanguageToggleTip"] = "Show the panel in Romanian",
        ["ConsentTitle"] = "Before you start",
        ["ConsentBody"] = "To answer questions, Revit AI sends what you type and parts of your model to the AI service you choose (OpenAI or Google Gemini): element names, categories, types, parameter values, levels and views. That service's API data policies apply. Nothing is sent until you accept.",
        ["ConsentAccept"] = "I understand, continue",
        ["KeyTitle"] = "AI service and API key",
        ["ModelLabel"] = "Model (optional)",
        ["ModelHint"] = "Leave empty for {0}. Get a key at {1}.",
        ["KeyLooksLikeOther"] = "This looks like a {0} key, but {1} is selected. Choose {0} above, then save the key again.",
        ["KeyHelp"] = "Choose the service and paste its API key. Each key is stored encrypted for your Windows account and only sent to its own service.",
        ["Save"] = "Save",
        ["Remove"] = "Remove",
        ["Preview"] = "Preview",
        ["PreviewTip"] = "Run the plan in Revit and roll it back, to see the real result and warnings",
        ["Apply"] = "Apply",
        ["ApplyTip"] = "Make these changes. They become one undo step (Ctrl+Z).",
        ["Discard"] = "Discard",
        ["Send"] = "Send",
        ["Cancel"] = "Cancel",
        ["Footer"] = "Nothing in your model changes until you click Apply. Each applied plan is one undo step (Ctrl+Z).",
        ["You"] = "You",
        ["Welcome"] = "Ask me about your model or what to change, for example: \"What did I select?\", \"How many doors are on this level?\", \"Make this wall 50 cm longer.\" I only propose changes; nothing changes until you click Apply.",
        ["NoProject"] = "No project open",
        ["SelectionOne"] = "{0} selected element",
        ["SelectionFew"] = "{0} selected elements",
        ["SelectionMany"] = "{0} selected elements",
        ["ProjectChangedConversation"] = "The active project changed, so I started a new conversation.",
        ["ProjectChangedPlan"] = "The active project changed, so I discarded the proposal. Nothing was changed.",
        ["PasteKeyFirst"] = "Paste the API key first.",
        ["KeySaved"] = "API key saved, encrypted for your Windows account.",
        ["KeySaveFailed"] = "I couldn't save the API key: {0}",
        ["KeyRemoved"] = "API key removed.",
        ["KeyRemoveFailed"] = "I couldn't remove the API key: {0}",
        ["AcceptNoticeFirst"] = "Please read and accept the data notice above first.",
        ["AddKeyFirst"] = "Choose an AI service and add its API key first, in the API key panel above.",
        ["PreviousPlanDiscarded"] = "I discarded the previous proposal; it was never applied.",
        ["Discarded"] = "Discarded the proposal. Nothing was changed.",
        ["Cancelled"] = "Cancelled.",
        ["OpenAiTimeout"] = "The AI service didn't answer within {0} seconds. Please try again.",
        ["CouldNotReachOpenAi"] = "I couldn't reach the AI service. Check your internet connection and try again.",
        ["SomethingWrong"] = "Something went wrong: {0}",
        ["AiInvalidKey"] = "The AI service rejected the API key. Check that the key belongs to the service selected in the API key panel above.",
        ["AiRateLimited"] = "The AI service's rate limit or quota was reached ({0}). Wait a moment, or check your plan with that service.",
        ["AiBadResponse"] = "The AI service returned an answer I couldn't read. Please try again.",
        ["AiFailed"] = "The AI request failed: {0}",
        ["AiBusy"] = "The AI service is busy right now, even after retrying ({0}). Try again in a minute, or choose another model in the API key panel.",
        ["RevitTimeout"] = "Revit didn't respond in time. It may be busy or showing a dialog; close it and try again.",
        ["ReadModelFailed"] = "I couldn't read the model: {0}",
        ["PlanHeader"] = "Proposed changes · not applied yet · operations: {0}",
        ["PlanPreviewRequired"] = " · preview required before Apply",
        ["StatusPreviewing"] = "Previewing in Revit. Nothing will be kept…",
        ["StatusApplying"] = "Applying changes in Revit…",
        ["PreviewTimeout"] = "Revit didn't start the preview in time (busy or showing a dialog). Nothing was changed. Try again.",
        ["ApplyTimeout"] = "Revit didn't start applying in time (busy or showing a dialog). Nothing was changed. Try again.",
        ["PreviewError"] = "Preview failed: {0}. Nothing was changed.",
        ["ApplyError"] = "Apply failed: {0}. Nothing was changed.",
        ["PreviewSucceeded"] = "Preview succeeded. It was rolled back, so nothing was kept:",
        ["PreviewFailedAtStep"] = "Preview failed at step {0}: {1}",
        ["PreviewAdjust"] = "Nothing was changed. Ask me to adjust the plan.",
        ["Applied"] = "Applied {0} change(s):",
        ["UndoHint"] = "Undo all of it with Ctrl+Z (\"{0}\").",
        ["ApplyFailedAtStep"] = "Nothing was changed. Step {0} ({1}) failed: {2}",
        ["StepsRolledBack"] = "Steps 1–{0} were rolled back too.",
        ["RevitWarning"] = "Revit warning: {0}",
        ["Thinking"] = "Thinking…",
        ["NoAnswer"] = "I don't have an answer for that.",
        ["StoppedAtLimit"] = "I stopped after {0} steps without reaching an answer. Try asking something more specific.",
        // Write tools and plan execution: plan lines, step outcomes and failure reasons.
        ["Tool.CatWalls"] = "walls",
        ["Tool.CatDoors"] = "doors",
        ["Tool.CatWindows"] = "windows",
        ["Tool.CatFloors"] = "floors",
        ["Tool.WallSummary"] = "Create wall '{0}' on {1}, {2} long, {3} high, from ({4:0}, {5:0}) to ({6:0}, {7:0})",
        ["Tool.WallCreated"] = "Created wall {0} ('{1}', {2}) on {3}",
        ["Tool.WallTooShort"] = "The wall would be {0} long; walls must be at least {1}.",
        ["Tool.WallHeightRange"] = "Wall height must be between 0 and {0}.",
        ["Tool.ModifyZero"] = "distanceMm must not be 0.",
        ["Tool.EndStart"] = "start",
        ["Tool.EndEnd"] = "end",
        ["Tool.ModifyReferenceSummary"] = "Change the length of {0} by {1:+0;-0} mm at its {2}",
        ["Tool.ModifySummary"] = "Wall {0}: {1} → {2} (moves its {3})",
        ["Tool.ModifyDone"] = "Wall {0}: {1} → {2}",
        ["Tool.ModifyTooShort"] = "Wall {0} is {1} long; it can't be shortened by {2}.",
        ["Tool.ModifyNotApplied"] = "Revit did not change wall {0} to {1}; it is still {2}.",
        ["Tool.RoomSummary"] = "Create room on {0} at ({1:0}, {2:0})",
        ["Tool.RoomSummaryNamed"] = "Create room '{0}' on {1} at ({2:0}, {3:0})",
        ["Tool.RoomNotEnclosed"] = "The point ({0:0}, {1:0}) isn't inside an area enclosed by walls or room separation lines, so the room would not be enclosed.",
        ["Tool.RoomCreated"] = "Created room {0} '{1}' ({2:0.##} m²) on {3}",
        ["Tool.Door"] = "door",
        ["Tool.Window"] = "window",
        ["Tool.WallRef"] = "wall {0}",
        ["Tool.HostedSummary"] = "Place {0} '{1}' in {2}, centred {3} from its start",
        ["Tool.SillSuffix"] = ", sill {0}",
        ["Tool.DoorPlaced"] = "Placed door {0} ('{1}') in wall {2}",
        ["Tool.WindowPlaced"] = "Placed window {0} ('{1}') in wall {2}",
        ["Tool.SillNotEditable"] = "Window type '{0}' has no editable sill height.",
        ["Tool.SillRange"] = "The sill height must be between 0 and {0}.",
        ["Tool.OffsetOutside"] = "The position {0} is outside the wall, which is {1} long.",
        ["Tool.NotHosted"] = "The {0} could not be hosted in wall {1}.",
        ["Tool.WallNoLevel"] = "Wall {0} has no base level.",
        ["Tool.FloorSummary"] = "Create floor '{0}' on {1}, {2} corners, {3:0.##} m²",
        ["Tool.FloorCreated"] = "Created floor {0} ('{1}', {2:0.##} m²) on {3}",
        ["Tool.FloorTooFewPoints"] = "A floor boundary needs at least 3 points.",
        ["Tool.FloorShortEdge"] = "Boundary edges must be at least {0} long (check for repeated points).",
        ["Tool.FloorSelfIntersects"] = "The boundary crosses or touches itself.",
        ["Tool.FloorNoArea"] = "The boundary encloses no area (are the points in a line?).",
        ["Tool.NotALevel"] = "Element {0} is not a level.",
        ["Tool.NotAWall"] = "Element {0} is not a wall.",
        ["Tool.NotStraight"] = "Wall {0} is not straight; only straight walls are supported.",
        ["Tool.NoDefaultType"] = "The project has no default type for {0}. Use the typeId of an existing element.",
        ["Tool.NotAType"] = "Element {0} is not a type for {1}.",
        ["Tool.WrongCategoryType"] = "Type {0} ({1}) is not a type for {2}.",
        ["Tool.IdOrReference"] = "{0} must be an element ID or a reference like $op1.elementId.",
        ["Tool.UnresolvedReference"] = "{0} still contains an unresolved reference.",
        ["Plan.NotWriteTool"] = "'{0}' is not an available write tool.",
        ["Plan.RevitRefused"] = "Revit refused the operation: {0}",
        ["Plan.NotAccepted"] = "Revit did not accept the change ({0}).",

        // Documentation tools (Phase 4).
        ["Tool.CatTitleBlocks"] = "title blocks",
        ["Tool.FloorPlan"] = "floor plan",
        ["Tool.CeilingPlan"] = "ceiling plan",
        ["Tool.ViewSummary"] = "Create {0} '{1}' for {2}",
        ["Tool.ViewSummaryUnnamed"] = "Create {0} for {1}",
        ["Tool.TemplateSuffix"] = ", template '{0}'",
        ["Tool.ViewCreated"] = "Created view {0} '{1}'",
        ["Tool.ViewNameTaken"] = "A view named '{0}' already exists.",
        ["Tool.NoViewFamilyType"] = "The project has no view type for a {0}.",
        ["Tool.NotATemplate"] = "Element {0} is not a view template.",
        ["Tool.SheetSummary"] = "Create sheet {0} '{1}' with title block '{2}'",
        ["Tool.SheetViewsSuffix"] = ", placing {0} view(s)",
        ["Tool.SheetCreated"] = "Created sheet {0} '{1}' (ID {2}) and placed {3} view(s)",
        ["Tool.SheetNumberTaken"] = "A sheet numbered '{0}' already exists.",
        ["Tool.SheetNumberEmpty"] = "The sheet number is empty.",
        ["Tool.NotAPlaceableView"] = "Element {0} is not a view that can be placed on a sheet.",
        ["Tool.ViewOnSheet"] = "View '{0}' is already on sheet {1}.",
        ["Tool.CannotPlaceView"] = "View '{0}' can't be placed on this sheet.",
        ["Tool.ScheduleSummary"] = "Create schedule '{0}' of {1} with fields: {2}",
        ["Tool.ScheduleCreated"] = "Created schedule {0} '{1}' with {2} field(s)",
        ["Tool.ScheduleNameTaken"] = "A schedule named '{0}' already exists.",
        ["Tool.ScheduleNoFields"] = "Give at least one field.",
        ["Tool.ScheduleUnknownField"] = "'{0}' is not a field of {1} schedules. Available fields include: {2}",
        ["Tool.ScheduleCategory"] = "{0} can't be scheduled.",
        ["Tool.TagSummary"] = "Tag {0} untagged {1} in view '{2}'",
        ["Tool.TagSummaryRef"] = "Tag untagged {0} in view {1}",
        ["Tool.TagSummaryIds"] = "Tag {0} element(s) in view '{1}'",
        ["Tool.TagsCreated"] = "Added {0} tag(s) in view '{1}'",
        ["Tool.NothingToTag"] = "There is nothing untagged to tag in view '{0}'.",
        ["Tool.ViewNotTaggable"] = "View '{0}' ({1}) can't hold tags; use a plan, section or elevation.",
        ["Tool.TagNeedsTarget"] = "Give either a category or elementIds, not both.",
        ["Tool.NotAView"] = "Element {0} is not a view.",
        ["Tool.TextSummary"] = "Add text \"{0}\" in view '{1}' at ({2:0}, {3:0})",
        ["Tool.TextCreated"] = "Added text note {0} in view '{1}'",
        ["Tool.TextEmpty"] = "The text is empty.",
        ["Tool.ViewNoAnnotation"] = "View '{0}' ({1}) can't hold annotations.",
        ["Tool.NoTextType"] = "The project has no default text type.",
        ["Tool.DimSummary"] = "Dimension {0} ({1}) in view '{2}', {3} from the wall",
        ["Tool.DimCreated"] = "Added dimension {0} ({1}) to wall {2}",
        ["Tool.DimNoEnds"] = "Couldn't find both end faces of wall {0} in this view (it may be joined to other walls at its ends).",
        ["Tool.ViewNotPlan"] = "View '{0}' is not a plan view.",
        ["Tool.NamedSuffix"] = " '{0}'",
        ["Tool.SectionSummary"] = "Create section{0} along ({1:0}, {2:0}) → ({3:0}, {4:0}), {5} deep, {6} high above {7}, looking to the left of that direction",
        ["Tool.SectionCreated"] = "Created section {0} '{1}'",
        ["Tool.SectionTooShort"] = "The section line must be at least {0} long.",
        ["Tool.SectionRange"] = "Depth and height must be between 0 and {0}.",
        ["Tool.North"] = "north",
        ["Tool.East"] = "east",
        ["Tool.South"] = "south",
        ["Tool.West"] = "west",
        ["Tool.ElevationSummary"] = "Create elevation(s) looking {0} from ({1:0}, {2:0}), with the marker in view '{3}'",
        ["Tool.ElevationCreated"] = "Created elevation view(s): {0}",
        ["Tool.ElevationNeedsDirection"] = "Give at least one direction.",
        ["Tool.ElevationNoSlot"] = "Couldn't create an elevation looking {0} from this marker.",
        ["Tool.ThreeDSummary"] = "Create 3D view{0}{1}",
        ["Tool.SectionBoxSuffix"] = ", cropped around {0} element(s)",
        ["Tool.ThreeDCreated"] = "Created 3D view {0} '{1}'",
        ["Tool.NoBoundingBox"] = "Element {0} has no geometry to crop around.",
        ["Tool.RoomDimSummary"] = "Dimension the width and depth of room {0} in view '{1}'",
        ["Tool.RoomDimCreated"] = "Added {0} dimension(s) to room {1}: {2}",
        ["Tool.NotARoom"] = "Element {0} is not a room.",
        ["Tool.RoomNotPlaced"] = "Room {0} is not placed or not enclosed.",
        ["Tool.RoomNoOppositeWalls"] = "Couldn't find two opposite straight walls around room {0} to dimension.",
        ["Tool.MoveSummary"] = "Move {0} element(s) by ({1:0}, {2:0}) mm: {3}",
        ["Tool.ElbowSummary"] = "Connect pipe {0} (Ø{1}) and pipe {2} (Ø{3}) with a {4:0}° elbow at ({5:0}, {6:0}, {7:0}); the pipe ends move {8:+0;-0;0} mm and {9:+0;-0;0} mm",
        ["Tool.ElbowSummaryRef"] = "Connect pipes {0} and {1} with an elbow at their corner",
        ["Tool.ElbowDone"] = "Connected pipes {0} and {1} with elbow {2}",
        ["Tool.ElbowFailed"] = "Revit could not insert the elbow ({0}). Check that the pipe type has elbows in its routing preferences.",
        ["Tool.NotAPipe"] = "Element {0} is not a straight pipe.",
        ["Tool.PipesSame"] = "Choose two different pipes.",
        ["Tool.PipeEndConnected"] = "The end of pipe {0} at the corner is already connected to something.",
        ["Tool.CornerParallel"] = "The pipes are parallel, so there is no corner. Pipes in a straight line can be merged instead.",
        ["Tool.CornerNoMeet"] = "The pipes don't meet: their centerlines pass {0} apart (for example at different heights).",
        ["Tool.CornerMiddle"] = "The pipes meet in the middle of a pipe; connect them with a tee instead.",
        ["Tool.CornerTooFar"] = "The pipes are too far from their corner (more than {0}).",
        ["Tool.CornerTooShort"] = "One of the pipes is too short.",
        ["Tool.MergeSummary"] = "Merge pipe {0} into pipe {1} (Ø{2}): one pipe of {3:0} mm. Pipe {0} is removed and its own parameter values (e.g. Mark, Comments) are lost",
        ["Tool.MergeSummaryCoupling"] = "Merge pipe {0} into pipe {1} (Ø{2}): one pipe of {3:0} mm. Pipe {0} and coupling {4} are removed; pipe {0}'s own parameter values (e.g. Mark, Comments) are lost",
        ["Tool.MergeSummaryRef"] = "Merge pipe {0} into pipe {1}",
        ["Tool.MergeDone"] = "Merged pipe {0} into pipe {1}, now {2:0} mm long",
        ["Tool.MergeDifferentType"] = "The pipes have different pipe types, so they can't become one pipe.",
        ["Tool.MergeDifferentSize"] = "The pipes have different diameters (Ø{0} and Ø{1}); that needs a reducer, which is not available yet.",
        ["Tool.MergeDifferentSystem"] = "The pipes belong to different system types, so they can't become one pipe.",
        ["Tool.MergeNotParallel"] = "The pipes are not in a straight line; to join them at an angle, connect them with an elbow.",
        ["Tool.MergeNotInLine"] = "The pipes are parallel but not in line: their centerlines are {0} apart.",
        ["Tool.MergeContained"] = "One pipe lies inside the other along the same line; merging would not change anything useful.",
        ["Tool.MergeTooFar"] = "The pipes are too far apart (more than {0}).",
        ["Tool.MergeJointBlocked"] = "Where pipes {0} and {1} meet there is something other than a plain coupling (e.g. a tee or valve), so they can't be merged.",
        ["Tool.MergeReconnectFailed"] = "Revit could not reconnect element {0} to the merged pipe.",
        ["Tool.MergeLengthWrong"] = "The merged pipe is {0} long instead of {1}.",
        ["Tool.TeeSummary"] = "Connect branch pipe {0} (Ø{1}) to main pipe {2} (Ø{3}) with a tee at ({4:0}, {5:0}, {6:0}); the main pipe is split there into two pipes and the branch end moves {7:+0;-0;0} mm",
        ["Tool.TeeSummaryRef"] = "Connect branch pipe {0} to main pipe {1} with a tee",
        ["Tool.TeeDone"] = "Connected branch pipe {0} to main pipe {1} with tee {2}; the other part of the main pipe is pipe {3}",
        ["Tool.TeeFailed"] = "Revit could not insert the tee ({0}). Check that the pipe type has tees in its routing preferences for these sizes.",
        ["Tool.TeeNotPerpendicular"] = "The branch is not at a right angle to the main pipe; angled branches are not available yet.",
        ["Tool.TeeNearMainEnd"] = "The branch meets the main pipe too close to its end (less than {0}); connect them with an elbow instead.",
        ["Tool.TeeCrossing"] = "The pipes cross each other; a tee needs the branch to end at the main pipe.",
        ["Tool.TeeTooFar"] = "The branch is too far from the main pipe (more than {0}).",
        ["Tool.TeeBranchConnected"] = "The end of branch pipe {0} at the main pipe is already connected to something.",
        ["Tool.MoveDone"] = "Moved {0} element(s) by ({1:0}, {2:0}) mm",
        ["Tool.MoveZero"] = "The move distance is zero.",
        ["Tool.MoveTooFar"] = "Moves are limited to {0}.",
        ["Tool.Pinned"] = "Element {0} is pinned; unpin it in Revit first.",
        ["Tool.MoveNeedsElements"] = "Give at least one element.",
        ["Tool.DeleteSummary"] = "Delete {0} element(s): {1}",
        ["Tool.DeleteDone"] = "Deleted {0} element(s), including {1} dependent element(s)",
        ["Tool.DeleteNotAllowed"] = "Element {0} ({1}) can't be deleted by Revit AI; only model elements and annotations can.",
        ["Tool.DeleteTooMany"] = "At most {0} elements can be deleted at once.",
        ["PlanDestructive"] = "⚠ This plan deletes elements. Preview it to see everything that will be removed, including dependent elements such as doors in a deleted wall.",
        ["ConfirmDelete"] = "I have checked the preview and want to delete these elements",
        ["Tool.SetSummary"] = "Set '{0}' = {1} on {2} element(s): {3}",
        ["Tool.SetDone"] = "Set '{0}' = {1} on {2} element(s)",
        ["Tool.ParamMissing"] = "Element {0} has no instance parameter '{1}'.",
        ["Tool.ParamOnType"] = "'{1}' is a type parameter of element {0}; changing it would change every element of that type, which is not supported.",
        ["Tool.ParamReadOnly"] = "Parameter '{1}' of element {0} is read-only.",
        ["Tool.ParamWrongValue"] = "Parameter '{1}' of element {0} needs {2}.",
        ["Tool.ParamElementId"] = "Parameter '{1}' of element {0} refers to another element and can't be set here.",
        ["Tool.ParamRejected"] = "Revit rejected the value for '{1}' on element {0}.",
        ["Tool.ParamUnits"] = "Parameter '{1}' of element {0} uses units that can't be set here (only mm, m², degrees and m³ are supported).",
        ["Tool.SetTooMany"] = "At most {0} elements can be changed at once.",
        ["Tool.GridsSummary"] = "Create {0} grid line(s): {1}",
        ["Tool.GridsDone"] = "Created {0} grid line(s): {1}",
        ["Tool.GridNameTaken"] = "A grid named '{0}' already exists.",
        ["Tool.GridNameEmpty"] = "Every grid needs a name.",
        ["Tool.GridNameRepeated"] = "The grid name '{0}' is used twice in this request.",
        ["Tool.GridTooShort"] = "Grid '{0}' would be shorter than {1}.",
        ["Tool.GridsTooMany"] = "At most {0} grid lines can be created at once.",
        ["Tool.PlaceSummary"] = "Place {0} × '{1}' on {2}{3}",
        ["Tool.PlaceRotation"] = ", rotated {0:0.#}°",
        ["Tool.PlaceDone"] = "Placed {0} × '{1}' on {2}",
        ["Tool.PlaceNotLevelBased"] = "'{0}' must be hosted (e.g. by a wall or face); only level-based families can be placed at points.",
        ["Tool.PlaceTooMany"] = "At most {0} elements can be placed at once.",
        ["Tool.PlaceNeedsPoints"] = "Give at least one point.",
        ["Tool.NotAFamilyType"] = "Element {0} is not a loadable family type.",
        ["Tool.ValueText"] = "text",
        ["Tool.ValueWholeNumber"] = "a whole number or yes/no",
        ["Tool.ValueNumber"] = "a number",
        ["Tool.TemplateSummary"] = "Apply view template '{0}' to {1} view(s): {2}",
        ["Tool.TemplateDone"] = "Applied view template '{0}' to {1} view(s)",
        ["Tool.TemplateInvalid"] = "Template '{0}' can't be applied to view '{1}' ({2}).",
    };


    internal static readonly IReadOnlyDictionary<string, string> RomanianStrings = new Dictionary<string, string>
    {
        ["Refresh"] = "Reîmprospătează",
        ["RefreshTip"] = "Citește contextul curent din Revit",
        ["ApiKey"] = "Cheie API",
        ["ApiKeyTip"] = "Alege serviciul AI și adaugă, schimbă sau șterge cheia lui API",
        ["LanguageToggle"] = "English",
        ["LanguageToggleTip"] = "Afișează panoul în engleză",
        ["ConsentTitle"] = "Înainte de a începe",
        ["ConsentBody"] = "Pentru a răspunde la întrebări, Revit AI trimite ce scrii și părți din modelul tău către serviciul AI ales (OpenAI sau Google Gemini): nume de elemente, categorii, tipuri, valori ale parametrilor, niveluri și vederi. Se aplică politicile acelui serviciu privind datele trimise prin API. Nu se trimite nimic până nu accepți.",
        ["ConsentAccept"] = "Am înțeles, continuă",
        ["KeyTitle"] = "Serviciul AI și cheia API",
        ["ModelLabel"] = "Model (opțional)",
        ["ModelHint"] = "Lasă gol pentru {0}. Obține o cheie de la {1}.",
        ["KeyLooksLikeOther"] = "Aceasta pare o cheie {0}, dar este selectat {1}. Alege {0} mai sus, apoi salvează din nou cheia.",
        ["KeyHelp"] = "Alege serviciul și lipește cheia lui API. Fiecare cheie este stocată criptat pentru contul tău Windows și trimisă doar către serviciul ei.",
        ["Save"] = "Salvează",
        ["Remove"] = "Șterge",
        ["Preview"] = "Previzualizează",
        ["PreviewTip"] = "Rulează planul în Revit și anulează-l, ca să vezi rezultatul real și avertismentele",
        ["Apply"] = "Aplică",
        ["ApplyTip"] = "Fă aceste modificări. Devin un singur pas de anulare (Ctrl+Z).",
        ["Discard"] = "Renunță",
        ["Send"] = "Trimite",
        ["Cancel"] = "Oprește",
        ["Footer"] = "Nimic nu se schimbă în model până nu apeși Aplică. Fiecare plan aplicat este un singur pas de anulare (Ctrl+Z).",
        ["You"] = "Tu",
        ["Welcome"] = "Întreabă-mă despre model sau ce să modific, de exemplu: „Ce am selectat?”, „Câte uși sunt pe acest nivel?”, „Prelungește acest perete cu 50 cm.” Eu doar propun modificări; nimic nu se schimbă până nu apeși Aplică.",
        ["NoProject"] = "Niciun proiect deschis",
        ["SelectionOne"] = "{0} element selectat",
        ["SelectionFew"] = "{0} elemente selectate",
        ["SelectionMany"] = "{0} de elemente selectate",
        ["ProjectChangedConversation"] = "Proiectul activ s-a schimbat, așa că am început o conversație nouă.",
        ["ProjectChangedPlan"] = "Proiectul activ s-a schimbat, așa că am renunțat la propunere. Nu s-a modificat nimic.",
        ["PasteKeyFirst"] = "Lipește mai întâi cheia API.",
        ["KeySaved"] = "Cheia API a fost salvată, criptată pentru contul tău Windows.",
        ["KeySaveFailed"] = "Nu am putut salva cheia API: {0}",
        ["KeyRemoved"] = "Cheia API a fost ștearsă.",
        ["KeyRemoveFailed"] = "Nu am putut șterge cheia API: {0}",
        ["AcceptNoticeFirst"] = "Te rog să citești și să accepți mai întâi notificarea despre date de mai sus.",
        ["AddKeyFirst"] = "Alege un serviciu AI și adaugă mai întâi cheia lui API, în panoul Cheie API de mai sus.",
        ["PreviousPlanDiscarded"] = "Am renunțat la propunerea anterioară; nu a fost aplicată.",
        ["Discarded"] = "Am renunțat la propunere. Nu s-a modificat nimic.",
        ["Cancelled"] = "Oprit.",
        ["OpenAiTimeout"] = "Serviciul AI nu a răspuns în timpul alocat ({0} s). Te rog să încerci din nou.",
        ["CouldNotReachOpenAi"] = "Nu am putut contacta serviciul AI. Verifică conexiunea la internet și încearcă din nou.",
        ["SomethingWrong"] = "Ceva nu a mers bine: {0}",
        ["AiInvalidKey"] = "Serviciul AI a respins cheia API. Verifică dacă cheia aparține serviciului ales în panoul Cheie API de mai sus.",
        ["AiRateLimited"] = "S-a atins limita de cereri sau cota serviciului AI ({0}). Așteaptă puțin sau verifică planul tău la acel serviciu.",
        ["AiBadResponse"] = "Serviciul AI a trimis un răspuns pe care nu l-am putut citi. Te rog să încerci din nou.",
        ["AiFailed"] = "Cererea către serviciul AI a eșuat: {0}",
        ["AiBusy"] = "Serviciul AI este ocupat acum, chiar și după reîncercări ({0}). Încearcă din nou peste un minut sau alege alt model în panoul Cheie API.",
        ["RevitTimeout"] = "Revit nu a răspuns la timp. Poate este ocupat sau afișează un dialog; închide-l și încearcă din nou.",
        ["ReadModelFailed"] = "Nu am putut citi modelul: {0}",
        ["PlanHeader"] = "Modificări propuse · neaplicate încă · operații: {0}",
        ["PlanPreviewRequired"] = " · previzualizarea este obligatorie înainte de Aplică",
        ["StatusPreviewing"] = "Previzualizare în Revit. Nu se va păstra nimic…",
        ["StatusApplying"] = "Se aplică modificările în Revit…",
        ["PreviewTimeout"] = "Revit nu a pornit previzualizarea la timp (este ocupat sau afișează un dialog). Nu s-a modificat nimic. Încearcă din nou.",
        ["ApplyTimeout"] = "Revit nu a pornit aplicarea la timp (este ocupat sau afișează un dialog). Nu s-a modificat nimic. Încearcă din nou.",
        ["PreviewError"] = "Previzualizarea a eșuat: {0}. Nu s-a modificat nimic.",
        ["ApplyError"] = "Aplicarea a eșuat: {0}. Nu s-a modificat nimic.",
        ["PreviewSucceeded"] = "Previzualizarea a reușit. A fost anulată, deci nu s-a păstrat nimic:",
        ["PreviewFailedAtStep"] = "Previzualizarea a eșuat la pasul {0}: {1}",
        ["PreviewAdjust"] = "Nu s-a modificat nimic. Cere-mi să ajustez planul.",
        ["Applied"] = "Am aplicat modificările ({0}):",
        ["UndoHint"] = "Anulezi totul cu Ctrl+Z („{0}”).",
        ["ApplyFailedAtStep"] = "Nu s-a modificat nimic. Pasul {0} ({1}) a eșuat: {2}",
        ["StepsRolledBack"] = "Au fost anulați și pașii 1–{0}.",
        ["RevitWarning"] = "Avertisment Revit: {0}",
        ["Thinking"] = "Mă gândesc…",
        ["NoAnswer"] = "Nu am un răspuns pentru asta.",
        ["StoppedAtLimit"] = "M-am oprit după {0} pași fără să ajung la un răspuns. Încearcă o întrebare mai precisă.",

        ["Tool.CatWalls"] = "pereți",
        ["Tool.CatDoors"] = "uși",
        ["Tool.CatWindows"] = "ferestre",
        ["Tool.CatFloors"] = "pardoseli",
        ["Tool.WallSummary"] = "Creează peretele „{0}” pe {1}, lung de {2}, înalt de {3}, de la ({4:0}, {5:0}) la ({6:0}, {7:0})",
        ["Tool.WallCreated"] = "Am creat peretele {0} („{1}”, {2}) pe {3}",
        ["Tool.WallTooShort"] = "Peretele ar avea {0}; un perete trebuie să aibă cel puțin {1}.",
        ["Tool.WallHeightRange"] = "Înălțimea peretelui trebuie să fie între 0 și {0}.",
        ["Tool.ModifyZero"] = "distanceMm nu poate fi 0.",
        ["Tool.EndStart"] = "capătul de început",
        ["Tool.EndEnd"] = "capătul de sfârșit",
        ["Tool.ModifyReferenceSummary"] = "Modifică lungimea pentru {0} cu {1:+0;-0} mm la {2}",
        ["Tool.ModifySummary"] = "Peretele {0}: {1} → {2} (se mută {3})",
        ["Tool.ModifyDone"] = "Peretele {0}: {1} → {2}",
        ["Tool.ModifyTooShort"] = "Peretele {0} are {1}; nu poate fi scurtat cu {2}.",
        ["Tool.ModifyNotApplied"] = "Revit nu a modificat peretele {0} la {1}; are în continuare {2}.",
        ["Tool.RoomSummary"] = "Creează o cameră pe {0} în punctul ({1:0}, {2:0})",
        ["Tool.RoomSummaryNamed"] = "Creează camera „{0}” pe {1} în punctul ({2:0}, {3:0})",
        ["Tool.RoomNotEnclosed"] = "Punctul ({0:0}, {1:0}) nu se află într-o zonă închisă de pereți sau de linii de separare, deci camera nu ar fi închisă.",
        ["Tool.RoomCreated"] = "Am creat camera {0} „{1}” ({2:0.##} m²) pe {3}",
        ["Tool.Door"] = "ușa",
        ["Tool.Window"] = "fereastra",
        ["Tool.WallRef"] = "peretele {0}",
        ["Tool.HostedSummary"] = "Plasează {0} „{1}” în {2}, centrată la {3} de la început",
        ["Tool.SillSuffix"] = ", parapet {0}",
        ["Tool.DoorPlaced"] = "Am plasat ușa {0} („{1}”) în peretele {2}",
        ["Tool.WindowPlaced"] = "Am plasat fereastra {0} („{1}”) în peretele {2}",
        ["Tool.SillNotEditable"] = "Tipul de fereastră „{0}” nu are înălțimea parapetului editabilă.",
        ["Tool.SillRange"] = "Înălțimea parapetului trebuie să fie între 0 și {0}.",
        ["Tool.OffsetOutside"] = "Poziția {0} este în afara peretelui, care are {1}.",
        ["Tool.NotHosted"] = "Elementul ({0}) nu a putut fi găzduit în peretele {1}.",
        ["Tool.WallNoLevel"] = "Peretele {0} nu are nivel de bază.",
        ["Tool.FloorSummary"] = "Creează pardoseala „{0}” pe {1}, {2} colțuri, {3:0.##} m²",
        ["Tool.FloorCreated"] = "Am creat pardoseala {0} („{1}”, {2:0.##} m²) pe {3}",
        ["Tool.FloorTooFewPoints"] = "Conturul pardoselii are nevoie de cel puțin 3 puncte.",
        ["Tool.FloorShortEdge"] = "Laturile conturului trebuie să aibă cel puțin {0} (verifică punctele repetate).",
        ["Tool.FloorSelfIntersects"] = "Conturul se intersectează sau se atinge singur.",
        ["Tool.FloorNoArea"] = "Conturul nu delimitează nicio suprafață (punctele sunt pe o linie?).",
        ["Tool.NotALevel"] = "Elementul {0} nu este un nivel.",
        ["Tool.NotAWall"] = "Elementul {0} nu este un perete.",
        ["Tool.NotStraight"] = "Peretele {0} nu este drept; sunt acceptați doar pereți drepți.",
        ["Tool.NoDefaultType"] = "Proiectul nu are un tip implicit pentru {0}. Folosește typeId-ul unui element existent.",
        ["Tool.NotAType"] = "Elementul {0} nu este un tip pentru {1}.",
        ["Tool.WrongCategoryType"] = "Tipul {0} ({1}) nu este un tip pentru {2}.",
        ["Tool.IdOrReference"] = "{0} trebuie să fie un ID de element sau o referință de forma $op1.elementId.",
        ["Tool.UnresolvedReference"] = "{0} conține încă o referință nerezolvată.",
        ["Plan.NotWriteTool"] = "„{0}” nu este o unealtă de modificare disponibilă.",
        ["Plan.RevitRefused"] = "Revit a refuzat operația: {0}",
        ["Plan.NotAccepted"] = "Revit nu a acceptat modificarea ({0}).",
        ["Tool.CatTitleBlocks"] = "cartușe",
        ["Tool.FloorPlan"] = "un plan de nivel",
        ["Tool.CeilingPlan"] = "un plan de tavan",
        ["Tool.ViewSummary"] = "Creează {0} „{1}” pentru {2}",
        ["Tool.ViewSummaryUnnamed"] = "Creează {0} pentru {1}",
        ["Tool.TemplateSuffix"] = ", șablon „{0}”",
        ["Tool.ViewCreated"] = "Am creat vederea {0} „{1}”",
        ["Tool.ViewNameTaken"] = "Există deja o vedere numită „{0}”.",
        ["Tool.NoViewFamilyType"] = "Proiectul nu are un tip de vedere pentru {0}.",
        ["Tool.NotATemplate"] = "Elementul {0} nu este un șablon de vedere.",
        ["Tool.SheetSummary"] = "Creează planșa {0} „{1}” cu cartușul „{2}”",
        ["Tool.SheetViewsSuffix"] = ", vederi de plasat: {0}",
        ["Tool.SheetCreated"] = "Am creat planșa {0} „{1}” (ID {2}); vederi plasate: {3}",
        ["Tool.SheetNumberTaken"] = "Există deja o planșă cu numărul „{0}”.",
        ["Tool.SheetNumberEmpty"] = "Numărul planșei este gol.",
        ["Tool.NotAPlaceableView"] = "Elementul {0} nu este o vedere care poate fi plasată pe o planșă.",
        ["Tool.ViewOnSheet"] = "Vederea „{0}” este deja pe planșa {1}.",
        ["Tool.CannotPlaceView"] = "Vederea „{0}” nu poate fi plasată pe această planșă.",
        ["Tool.ScheduleSummary"] = "Creează tabelul „{0}” pentru {1}, cu câmpurile: {2}",
        ["Tool.ScheduleCreated"] = "Am creat tabelul {0} „{1}”; câmpuri: {2}",
        ["Tool.ScheduleNameTaken"] = "Există deja un tabel numit „{0}”.",
        ["Tool.ScheduleNoFields"] = "Indică cel puțin un câmp.",
        ["Tool.ScheduleUnknownField"] = "„{0}” nu este un câmp pentru tabelele de {1}. Câmpuri disponibile, de exemplu: {2}",
        ["Tool.ScheduleCategory"] = "Pentru {0} nu se poate crea un tabel.",
        ["Tool.TagSummary"] = "Adaugă etichete pentru {1} fără etichetă în vederea „{2}” (elemente: {0})",
        ["Tool.TagSummaryRef"] = "Adaugă etichete pentru {0} fără etichetă în vederea {1}",
        ["Tool.TagSummaryIds"] = "Adaugă etichete pentru elementele indicate în vederea „{1}” (elemente: {0})",
        ["Tool.TagsCreated"] = "Am adăugat etichete în vederea „{1}”: {0}",
        ["Tool.NothingToTag"] = "Nu există elemente fără etichetă în vederea „{0}”.",
        ["Tool.ViewNotTaggable"] = "Vederea „{0}” ({1}) nu poate avea etichete; folosește un plan, o secțiune sau o fațadă.",
        ["Tool.TagNeedsTarget"] = "Indică fie o categorie, fie elementIds, nu amândouă.",
        ["Tool.NotAView"] = "Elementul {0} nu este o vedere.",
        ["Tool.TextSummary"] = "Adaugă textul „{0}” în vederea „{1}” la ({2:0}, {3:0})",
        ["Tool.TextCreated"] = "Am adăugat nota de text {0} în vederea „{1}”",
        ["Tool.TextEmpty"] = "Textul este gol.",
        ["Tool.ViewNoAnnotation"] = "Vederea „{0}” ({1}) nu poate conține adnotări.",
        ["Tool.NoTextType"] = "Proiectul nu are un tip de text implicit.",
        ["Tool.DimSummary"] = "Cotează {0} ({1}) în vederea „{2}”, la {3} de perete",
        ["Tool.DimCreated"] = "Am adăugat cota {0} ({1}) peretelui {2}",
        ["Tool.DimNoEnds"] = "Nu am găsit ambele fețe de capăt ale peretelui {0} în această vedere (poate este îmbinat cu alți pereți la capete).",
        ["Tool.ViewNotPlan"] = "Vederea „{0}” nu este o vedere în plan.",
        ["Tool.NamedSuffix"] = " „{0}”",
        ["Tool.SectionSummary"] = "Creează secțiunea{0} de-a lungul ({1:0}, {2:0}) → ({3:0}, {4:0}), adâncime {5}, înălțime {6} peste {7}, privind spre stânga acestei direcții",
        ["Tool.SectionCreated"] = "Am creat secțiunea {0} „{1}”",
        ["Tool.SectionTooShort"] = "Linia secțiunii trebuie să aibă cel puțin {0}.",
        ["Tool.SectionRange"] = "Adâncimea și înălțimea trebuie să fie între 0 și {0}.",
        ["Tool.North"] = "nord",
        ["Tool.East"] = "est",
        ["Tool.South"] = "sud",
        ["Tool.West"] = "vest",
        ["Tool.ElevationSummary"] = "Creează fațade orientate spre {0} din punctul ({1:0}, {2:0}), cu marcajul în vederea „{3}”",
        ["Tool.ElevationCreated"] = "Am creat fațadele: {0}",
        ["Tool.ElevationNeedsDirection"] = "Indică cel puțin o direcție.",
        ["Tool.ElevationNoSlot"] = "Nu am putut crea o fațadă orientată spre {0} din acest marcaj.",
        ["Tool.ThreeDSummary"] = "Creează o vedere 3D{0}{1}",
        ["Tool.SectionBoxSuffix"] = ", decupată în jurul elementelor: {0}",
        ["Tool.ThreeDCreated"] = "Am creat vederea 3D {0} „{1}”",
        ["Tool.NoBoundingBox"] = "Elementul {0} nu are geometrie în jurul căreia să se decupeze.",
        ["Tool.RoomDimSummary"] = "Cotează lățimea și adâncimea camerei {0} în vederea „{1}”",
        ["Tool.RoomDimCreated"] = "Am adăugat cote camerei {1} ({0}): {2}",
        ["Tool.NotARoom"] = "Elementul {0} nu este o cameră.",
        ["Tool.RoomNotPlaced"] = "Camera {0} nu este plasată sau nu este închisă.",
        ["Tool.RoomNoOppositeWalls"] = "Nu am găsit doi pereți drepți opuși în jurul camerei {0} pentru cotare.",
        ["Tool.MoveSummary"] = "Mută elementele ({0}) cu ({1:0}, {2:0}) mm: {3}",
        ["Tool.ElbowSummary"] = "Conectează țeava {0} (Ø{1}) și țeava {2} (Ø{3}) cu un cot de {4:0}° în punctul ({5:0}, {6:0}, {7:0}); capetele țevilor se mută cu {8:+0;-0;0} mm și {9:+0;-0;0} mm",
        ["Tool.ElbowSummaryRef"] = "Conectează țevile {0} și {1} cu un cot la colțul lor",
        ["Tool.ElbowDone"] = "Am conectat țevile {0} și {1} cu cotul {2}",
        ["Tool.ElbowFailed"] = "Revit nu a putut insera cotul ({0}). Verifică dacă tipul de țeavă are coturi în preferințele de rutare.",
        ["Tool.NotAPipe"] = "Elementul {0} nu este o țeavă dreaptă.",
        ["Tool.PipesSame"] = "Alege două țevi diferite.",
        ["Tool.PipeEndConnected"] = "Capătul țevii {0} de la colț este deja conectat la altceva.",
        ["Tool.CornerParallel"] = "Țevile sunt paralele, deci nu au un colț. Țevile în linie dreaptă pot fi unite în schimb.",
        ["Tool.CornerNoMeet"] = "Țevile nu se întâlnesc: axele lor trec la {0} una de alta (de exemplu la înălțimi diferite).",
        ["Tool.CornerMiddle"] = "Țevile se întâlnesc la mijlocul unei țevi; conectează-le cu un teu în schimb.",
        ["Tool.CornerTooFar"] = "Țevile sunt prea departe de colțul lor (peste {0}).",
        ["Tool.CornerTooShort"] = "Una dintre țevi este prea scurtă.",
        ["Tool.MergeSummary"] = "Unește țeava {0} cu țeava {1} (Ø{2}): o singură țeavă de {3:0} mm. Țeava {0} este eliminată, iar valorile parametrilor ei (de ex. Mark, Comments) se pierd",
        ["Tool.MergeSummaryCoupling"] = "Unește țeava {0} cu țeava {1} (Ø{2}): o singură țeavă de {3:0} mm. Țeava {0} și mufa {4} sunt eliminate; valorile parametrilor țevii {0} (de ex. Mark, Comments) se pierd",
        ["Tool.MergeSummaryRef"] = "Unește țeava {0} cu țeava {1}",
        ["Tool.MergeDone"] = "Am unit țeava {0} cu țeava {1}, care are acum {2:0} mm",
        ["Tool.MergeDifferentType"] = "Țevile au tipuri diferite, deci nu pot deveni o singură țeavă.",
        ["Tool.MergeDifferentSize"] = "Țevile au diametre diferite (Ø{0} și Ø{1}); pentru asta e nevoie de o reducție, care nu este disponibilă încă.",
        ["Tool.MergeDifferentSystem"] = "Țevile aparțin unor tipuri de sistem diferite, deci nu pot deveni o singură țeavă.",
        ["Tool.MergeNotParallel"] = "Țevile nu sunt în linie dreaptă; pentru a le uni în unghi, conectează-le cu un cot.",
        ["Tool.MergeNotInLine"] = "Țevile sunt paralele, dar nu în linie: axele lor sunt la {0} una de alta.",
        ["Tool.MergeContained"] = "O țeavă se află în interiorul celeilalte pe aceeași linie; unirea nu ar schimba nimic util.",
        ["Tool.MergeTooFar"] = "Țevile sunt prea departe una de alta (peste {0}).",
        ["Tool.MergeJointBlocked"] = "Acolo unde se întâlnesc țevile {0} și {1} există altceva decât o simplă mufă (de ex. un teu sau o vană), deci nu pot fi unite.",
        ["Tool.MergeReconnectFailed"] = "Revit nu a putut reconecta elementul {0} la țeava unită.",
        ["Tool.MergeLengthWrong"] = "Țeava unită are {0} în loc de {1}.",
        ["Tool.TeeSummary"] = "Conectează ramificația {0} (Ø{1}) la țeava principală {2} (Ø{3}) cu un teu în punctul ({4:0}, {5:0}, {6:0}); țeava principală este împărțită acolo în două țevi, iar capătul ramificației se mută cu {7:+0;-0;0} mm",
        ["Tool.TeeSummaryRef"] = "Conectează ramificația {0} la țeava principală {1} cu un teu",
        ["Tool.TeeDone"] = "Am conectat ramificația {0} la țeava principală {1} cu teul {2}; cealaltă parte a țevii principale este țeava {3}",
        ["Tool.TeeFailed"] = "Revit nu a putut insera teul ({0}). Verifică dacă tipul de țeavă are teuri în preferințele de rutare pentru aceste dimensiuni.",
        ["Tool.TeeNotPerpendicular"] = "Ramificația nu este în unghi drept cu țeava principală; ramificațiile în unghi nu sunt disponibile încă.",
        ["Tool.TeeNearMainEnd"] = "Ramificația întâlnește țeava principală prea aproape de capăt (sub {0}); conectează-le cu un cot în schimb.",
        ["Tool.TeeCrossing"] = "Țevile se intersectează; pentru un teu, ramificația trebuie să se termine la țeava principală.",
        ["Tool.TeeTooFar"] = "Ramificația este prea departe de țeava principală (peste {0}).",
        ["Tool.TeeBranchConnected"] = "Capătul ramificației {0} de la țeava principală este deja conectat la altceva.",
        ["Progress.connect_pipes_with_elbow"] = "Verific colțul țevilor…",
        ["Progress.merge_pipes"] = "Verific țevile de unit…",
        ["Progress.connect_pipes_with_tee"] = "Verific racordul cu teu…",
        ["Progress.query_elements"] = "Interoghez modelul…",
        ["Progress.check_pipe_systems"] = "Verific sistemele de țevi…",
        ["Tool.MoveDone"] = "Am mutat elementele ({0}) cu ({1:0}, {2:0}) mm",
        ["Tool.MoveZero"] = "Distanța de mutare este zero.",
        ["Tool.MoveTooFar"] = "Mutările sunt limitate la {0}.",
        ["Tool.Pinned"] = "Elementul {0} este fixat (pinned); anulează fixarea în Revit mai întâi.",
        ["Tool.MoveNeedsElements"] = "Indică cel puțin un element.",
        ["Tool.DeleteSummary"] = "Șterge elementele ({0}): {1}",
        ["Tool.DeleteDone"] = "Am șters elementele ({0}), inclusiv elemente dependente: {1}",
        ["Tool.DeleteNotAllowed"] = "Elementul {0} ({1}) nu poate fi șters de Revit AI; se pot șterge doar elemente de model și adnotări.",
        ["Tool.DeleteTooMany"] = "Se pot șterge cel mult {0} elemente odată.",
        ["PlanDestructive"] = "⚠ Acest plan șterge elemente. Previzualizează-l ca să vezi tot ce va fi eliminat, inclusiv elementele dependente, de exemplu ușile dintr-un perete șters.",
        ["ConfirmDelete"] = "Am verificat previzualizarea și vreau să șterg aceste elemente",
        ["Tool.SetSummary"] = "Setează „{0}” = {1} pentru elementele ({2}): {3}",
        ["Tool.SetDone"] = "Am setat „{0}” = {1} pentru elementele ({2})",
        ["Tool.ParamMissing"] = "Elementul {0} nu are parametrul de instanță „{1}”.",
        ["Tool.ParamOnType"] = "„{1}” este un parametru de tip al elementului {0}; modificarea lui ar schimba toate elementele de acel tip, ceea ce nu este permis.",
        ["Tool.ParamReadOnly"] = "Parametrul „{1}” al elementului {0} este doar pentru citire.",
        ["Tool.ParamWrongValue"] = "Parametrul „{1}” al elementului {0} are nevoie de {2}.",
        ["Tool.ParamElementId"] = "Parametrul „{1}” al elementului {0} face referire la alt element și nu poate fi setat aici.",
        ["Tool.ParamRejected"] = "Revit a respins valoarea pentru „{1}” la elementul {0}.",
        ["Tool.ParamUnits"] = "Parametrul „{1}” al elementului {0} folosește unități care nu pot fi setate aici (sunt acceptate doar mm, m², grade și m³).",
        ["Tool.SetTooMany"] = "Se pot modifica cel mult {0} elemente odată.",
        ["Tool.GridsSummary"] = "Creează axe ({0}): {1}",
        ["Tool.GridsDone"] = "Am creat axele ({0}): {1}",
        ["Tool.GridNameTaken"] = "Există deja o axă numită „{0}”.",
        ["Tool.GridNameEmpty"] = "Fiecare axă are nevoie de un nume.",
        ["Tool.GridNameRepeated"] = "Numele de axă „{0}” apare de două ori în această cerere.",
        ["Tool.GridTooShort"] = "Axa „{0}” ar fi mai scurtă de {1}.",
        ["Tool.GridsTooMany"] = "Se pot crea cel mult {0} axe odată.",
        ["Tool.PlaceSummary"] = "Plasează {0} × „{1}” pe {2}{3}",
        ["Tool.PlaceRotation"] = ", rotit cu {0:0.#}°",
        ["Tool.PlaceDone"] = "Am plasat {0} × „{1}” pe {2}",
        ["Tool.PlaceNotLevelBased"] = "„{0}” trebuie găzduit (de exemplu de un perete sau o față); doar familiile bazate pe nivel pot fi plasate în puncte.",
        ["Tool.PlaceTooMany"] = "Se pot plasa cel mult {0} elemente odată.",
        ["Tool.PlaceNeedsPoints"] = "Indică cel puțin un punct.",
        ["Tool.NotAFamilyType"] = "Elementul {0} nu este un tip de familie încărcabilă.",
        ["Progress.find_grid_lines"] = "Caut rândurile și coloanele de puncte…",
        ["Progress.create_grids"] = "Verific axele…",
        ["Progress.place_family_instances"] = "Verific amplasarea elementelor…",
        ["Progress.report_unavailable_request"] = "Notez cererea…",
        ["Tool.ValueText"] = "un text",
        ["Tool.ValueWholeNumber"] = "un număr întreg sau da/nu",
        ["Tool.ValueNumber"] = "un număr",
        ["Tool.TemplateSummary"] = "Aplică șablonul de vedere „{0}” la vederile ({1}): {2}",
        ["Tool.TemplateDone"] = "Am aplicat șablonul de vedere „{0}” la vederile ({1})",
        ["Tool.TemplateInvalid"] = "Șablonul „{0}” nu poate fi aplicat vederii „{1}” ({2}).",
        ["Progress.check_standards"] = "Verific standardele companiei…",
        ["Progress.get_project_standards"] = "Citesc standardele proiectului…",
        ["Progress.set_parameters"] = "Verific valorile parametrilor…",
        ["Progress.apply_view_template"] = "Verific șablonul de vedere…",
        ["Progress.get_workflow"] = "Citesc pașii fluxului de lucru…",
        ["Progress.delete_elements"] = "Verific ștergerea…",
        ["Progress.move_elements"] = "Verific mutarea…",
        ["Progress.select_elements"] = "Selectez elementele în Revit…",
        ["Progress.find_rooms_without_tags"] = "Caut camerele fără etichetă…",
        ["Progress.find_unhosted_doors"] = "Caut ușile fără perete gazdă…",
        ["Progress.find_unhosted_windows"] = "Caut ferestrele fără perete gazdă…",
        ["Progress.find_duplicate_elements"] = "Caut elementele duplicate…",
        ["Progress.get_model_warnings"] = "Citesc avertismentele modelului…",
        ["Progress.find_nonstandard_elements"] = "Caut elementele care nu respectă standardele…",
        ["Progress.find_elements_missing_parameter"] = "Caut parametrii lipsă…",
        ["Progress.create_section"] = "Verific secțiunea…",
        ["Progress.create_elevations"] = "Verific fațadele…",
        ["Progress.create_3d_view"] = "Verific vederea 3D…",
        ["Progress.dimension_room"] = "Verific cotele camerei…",
        ["Progress.find_views"] = "Caut vederile…",
        ["Progress.create_view"] = "Verific vederea…",
        ["Progress.create_sheet"] = "Verific planșa…",
        ["Progress.create_schedule"] = "Verific tabelul…",
        ["Progress.tag_elements"] = "Verific etichetele…",
        ["Progress.create_text"] = "Verific textul…",
        ["Progress.dimension_wall"] = "Verific cota…",

        // Tool progress labels; English falls back to each tool's own ProgressLabel.
        ["Progress.get_project_info"] = "Citesc informațiile proiectului…",
        ["Progress.get_active_view"] = "Citesc vederea activă…",
        ["Progress.get_active_level"] = "Citesc nivelul activ…",
        ["Progress.get_selected_elements"] = "Citesc selecția…",
        ["Progress.get_element"] = "Citesc elementul…",
        ["Progress.find_elements"] = "Caut în model…",
        ["Progress.get_element_parameters"] = "Citesc parametrii…",
        ["Progress.find_family_types"] = "Caut tipurile disponibile…",
        ["Progress.get_project_standard_types"] = "Citesc tipurile standard ale proiectului…",
        ["Progress.find_nearby_elements"] = "Caut elementele din apropiere…",
        ["Progress.get_element_room"] = "Caut camera elementului…",
        ["Progress.get_room_boundary"] = "Citesc limitele camerei…",
        ["Progress.create_wall"] = "Verific peretele…",
        ["Progress.modify_wall"] = "Verific modificarea peretelui…",
        ["Progress.create_room"] = "Verific camera…",
        ["Progress.create_door"] = "Verific ușa…",
        ["Progress.create_window"] = "Verific fereastra…",
        ["Progress.create_floor"] = "Verific pardoseala…",
    };
}
